package commands

import (
	"math/rand"

	"github.com/bwmarrin/discordgo"
)

func init() {
	Commands[cmdJoke.Name] = &Command{
		ApplicationCommand: cmdJoke,
		Handler:            handleJoke,
	}
}

var cmdJoke = &discordgo.ApplicationCommand{
	Type:        discordgo.ChatApplicationCommand,
	Name:        "joke",
	Description: "The best dad jokes on Discord!",
}

func handleJoke(ds *discordgo.Session, ic *discordgo.InteractionCreate) (*discordgo.InteractionResponseData, error) {
	return ContentResponse(jokes[rand.Intn(len(jokes))]), nil
}

var jokes = []string{
	"I attached all my watches together to make a belt.. It was a waist of time.",
	"I swallowed some food coloring and now I feel like I've dyed a little inside.",
	"I changed my iPod's name to Titanic, now it's syncing.",
	"Why are fish so easy to weight??  Because they have their own scales.",
	"I bought a pair of shoes from a drug dealer today.  I don't know what he laced them with but I've been tripping all day.",
	"Originally, I didn't like having a beard.  But, then it kind of grew on me.",
	"How come Barbie never got pregnant?  Because Ken always came in another box.",
	"Hey, there's a new movie called **Constipation**, it hasn't come out yet.",
	"What's the difference between a snowman and a snow woman?  Snowballs.",
	"How many tickles does it take to make a squid laugh?  Ten-tickles.",
	"I once swallowed two pieces of string and an hour later they came out tied together.  I shit you knot.",
	"Do you know how Moses makes coffee?  Hebrews it.",
	"What's the most famous fish in the sea? It's a starfish...  If you know a better fish pun, let minnow.",
	"What's the difference between tuna, a piano, and glue?  You can tuna piano but you can't tuna fish...",
	"Did you hear about that recent kidnapping at school?  It's okay though, he woke up.",
	"I remember the first time I saw a universal remote.  I thought to myself, \"Well, this changes everything.\"",
	"Archaeology really is a career in ruins...",
	"I don't trust stairs.  They're always up to something.",
	"My Czech mate is surprisingly bad at chess.",
	"What do you call a fat psychic? A four-chin teller.",
	"Man, I really hate perforated lines, they're tearable.",
	"A man tried to sell me a coffin today... I told him that's the last thing I need.",
	"Don't kiss your wife with a runny nose.  You might think it's funny, but it's snot.",
	"When my wife told me to stop impersonating a flamingo I had to put my foot down.",
	"What's the difference between a hippo and a zippo? One is really heavy, the other is a little lighter.",
	"To the man in the wheelchair that stole my digital camouflage jacket... You can hide, but you can't run.",
	"The other day I deleted the phone numbers of all the Germans I know from my mobile phone.  Now it's hans free.",
	"Why can't you hear a pterodactyl using the bathroom? Because the P is silent.",
	"Did you hear about the crazy Mexican train theif?!  He had loco motives.",
	"Singing in the shower is all fun and games until you get shampoo in your mouth... Then it's a soap opera.",
	"The rotation of earth really makes my day.",
	"You can't run though a camp site.  You can only ran, because it's past tents.",
	"Why do you never see elephants hiding in trees?  Because they're so good at it.",
	"So, a pirate walks into a bar with a sheep's wheel on his belt buckle.  The bartender asks, What's that on your belt?  To which the pirate said, Arrr, it's drivin' me nuts!",
	"What's orange and sounds like a parrot?  A carrot.",
	"What's brown and sticky?  A stick.",
	"How do you find Will Smith in the snow? You look for the fresh prints.",
	"There are two types of people in the world. Those who can extrapolate from incomplete data...",
	"So this furniture store keeps calling me.. But all I wanted was one night stand.",
	"Hey, did you hear about the guy who invented Lifesavers? They say he made a mint.",
	"A ham sandwich walks into a bar and orders a drink. Bartender says, Sorry we don't serve food here.",
	"Why do chicken coops only have two doors? Because if they had four, they would be chicken sedans!",
	"How do you make a tissue dance? Put a little boogie in it!",
	"Two peanuts were walking down the street.  One was a salted.",
	"How do you make holy water? You boil the hell out of it.",
	"Two guys walk into a bar, the third one ducks.",
	"I had a dream that I was a muffler last night.  I woke up exhausted!",
	"How do you tell the difference between a frog and a horny toad? A frog says Ribbit, Ribbit, and a horney toad says, Rubit, Rubit",
	"The other day I helped Forrest Gump setup his e-mail, his password was 1forrest1.",
	"What's the difference between a poorly dressed man on a tricycle and a well dressed man on a bicycle? Attire.",
	"Why do bears have hairy coats? Fur protection.",
	"What did t he pirate say on his 80th birthday? Aye Matey!",
	"Why did the A go to the bathroom and come out as an E? Because he had a vowel movement.",
	"Did you hear about the cheese factory that exploded in France? It was a muenster of an explosion and bleu everything to peices. The american was fine but the swiss was not so gouda. In the end, there was nothing left but de Brie.",
	"Do you know where you can get chicken broth in bulk?  The stock market.",
	"Why are skeletons so calm??  Because nothing gets under their skin.",
	"Have you ever noticed how remarkable whiteboards are?",
	"The other day I went to buy some camouflage pants but I couldn't find any.",
	"The other day I held a door open for a clown. It was a nice jester.",
	"I used to be addicted to soap... but I'm clean now.",
	"I've been making a list of reasons to move to switzerland.  The flag is a big plus.",
	"I'm terrified of elevators. I'll be taking steps to avoid them.",
	"Without nipples boobs would be pointless.",
	"Having sex in an elevator is wrong on so many levels.",
	"How do you know when you are going to drown in milk? When its pasteurized!",
	"Milk is the fastest liquid on earth, its pasteurized before you even see it.",
	"A steak pun is a rare medium well done.",
	`Did you hear about the new restaurant on the moon? The food is great, but there's just no atmosphere.`,
	`When you have a bladder infection, urine trouble.`,
	`A termite walks into a bar and asks "Is the bar tender here?"`,
	`Why did the octopus beat the shark in a fight? Because it was well armed.`,
	`Last night me and my girlfriend watched three DVDs back to back. Luckily I was the one facing the TV.`,
	`Trying to catch up with the times I setup speed dial on my phone. I added my grandma and now I've got instagram.`,
	`I fear for the calendar, its days are numbered.`,
	`They laughed when I said I wanted to be a comedian - they're not laughing now.`,
	`Why did the scarecrow win an award? Because he was outstanding in his field.`,
	`How do you stop an Internet troll?  Seize their memes of products`,
	`What do you called a psychic midget whose escaped from jail? a small medium at large.`,
	`Whats better than roses on your piano? Tulips on your organ.`,
	`What do you call a cow that quit producing milk?  An udder failure.`,
	`Cologne that doesn't have a smell makes no scents.`,
	`Petri dishes are always culturally relevent`,
	`What did the Amish woman wish for?  Two Mennonite.`,
	`What do you call a crazy guy in a room full of mosquitoes?  A bit neurotic.`,
	`Why can't a sidewalk be three feet long?  Because then it would be a yard.`,
	`I just read a book about Stockholm syndrome.  It was pretty bad at first, but by the end I liked it.`,
	`I stayed up all night wondering where the sun went, then it dawned on me.`,
	`After a great deal of reflection I've realized that quality testing mirrors is a job I could really see myself doing.`,
	`They're finally making a movie called "Clocks". It's about time.`,
	`I will never date another apostrophe....  The last one was too possessive.`,
	`I don't joke about funerals...  It's a grave matter.. I'm dead serious.`,
	`I've been trying to learn how to carve wood. I have been practicing it whittle by whitte.`,
	`What happens when frogs park illegally? They get toad.`,
	`Socialist jokes are not funny.  Unless everybody gets them.`,
	`When is a car no longer a car? When it turns into a driveway.`,
	`I used to be a banker, but I lost interest.`,
	`You could say that getting addicted to skiing is a slippery slope.`,
	`Recently, a man has taken an airline to court over mishandled luggage.  Unfortunately the man lost his case.`,
	`My son recently became a father for the first time and he asked where I stored my jokes. I told him him they're all in my dadabase.`,
	`I once told Skippy that he should embrace his mistakes. He hugged me.`,
	`Yesterday, I called to get a reservation at the Library, they told me they were all booked.`,
	`Well. That's a deep subject.`,
	`I recently got a new blender but I'm not sure if I like it. I keep getting mixed results.`,
	`I don't always tell dad jokes, but when I do, he laughs.`,
	`If you're skydiving and your parachute cord is tangled, don't worry about it.  You've got the rest of your life to figure it out.`,
	`It's hard to explain my jokes to kleptomaniacs because they always take things literally.`,
	`You can never lose a homing pigeion. If it doesn't fly back all you've lost is a pigeon.`,
	`The first time I got my hands on a universal remote, I thought.. "This changes everything!"`,
	`Why was the man such best friends with his step ladder? Because he never knew his real ladder.`,
	`They asked me how well I understood theoretical physics.  I said I had a theoretical degree in physics.`,
	`Two files are sitting on a pile of shit when a third fly comes up and says, "Pardon me, is this stool taken?"`,
	`So the other day I saw this car on the freeway that looked like a banana. Tried to pass it and it peeled off.`,
	`I know this guy who's addicted to brake fluid. I worry about him a lot, but he tells me he can stop anytime.`,
	`Did you hear about the Indian that drank too much tea? The next day he was found dead, he drowned in his teapee.`,
	`The lord said to John, come forth and you shall have enternal life.   Unfortantly John finished fifth and got a toaster.`,
	`Got a friend in North Korea that I called up the other day.   Asked him how things are going, he said "I can't complain".`,
	`I saw an ad in a shop window the said "Television for Sale - $1 - Volume Stick On Full".  I thought: "I can't turn that down".`,
	`We need to add three more states to the United States of America. That would make 53, a prime number, indivisible and justice for all.`,
	`I saw this mexican magician this weekend who did a disapearing act. He stood up in front of everyone and says uno, dos, and then left without a tres.`,
	`What's your feets favorite food? Shoeshi`,
	`When is a door not a door? when it's a jar.`,
	`What's another name for a Will?  Dead giveaway.`,
	`Where do poor meatballs live? In the speghetto.`,
	`What do you call a dog magician? A labra-cadabra-dor.`,
	`What did the sushi roll say to the other roll? Wasabi!`,
	`How do you catch a bra in the wild?  With a booby trap.`,
	`Why did the fly jump off the toilet? It got pissed off.`,
	`Why did the car crusher quit his job?  He got depressed.`,
	`Did you hear that they're not making yard sticks any longer?`,
	`I used to have a job collecting leaves.  I was raking it in.`,
	`The past, present, and future walk into a bar.  It was tense.`,
	`You know, I just have never liked bananas.  They lack appeal.`,
	`How much does a pirate pay for corn on the cob? A buck n' ear.`,
	`Why did the can crusher quit his job? Because it was soda pressing.`,
	`Two flies are arguing on a toilet seat when...  one gets pissed off!`,
	`What happens when two slugs get mad at each other?  They slug it out.`,
	`How did the hipster burn his lips? Drank is coffee before it was coool.`,
	`How do you get a D&D player to go out with you? You ask them for a d8.`,
	`What's the difference between in-laws and outlaws?  Outlaws are wanted.`,
	`There are 10 types of people. Those who understand binary and those who don't.`,
	`Feeling cold?  Go stand in a corner for a bit, they're usually around 90 degress.`,
	`What does Winnie the Poo and Alaxander the Great have in common? Same middle name.`,
	`Why are there no knock knock jokes about America?  ...because freedom rings.`,
	`Whatever you do, don't spell part backards..  It's a trap.`,
	`My friend died because nobody could remember his blood type.  As he passed away, he kept saying "Be Positive" but it's really hard without him.`,
	`My fellow bots are like Christmas lights.. Half of them don't work and the other half aren't that bright.`,
	`Why did the iPad go to the dentist?  Because it had a blutooth.`,
	`What did the hungry clock do?  It went back four seconds.`,
	`Which American president was the least guilty? Abraham Lincoln.  He was in a cent.`,
	`Why was the archaeologist so depressed? His life was in ruins.`,
	`What do mermaids wash their fins with?  Tide.`,
	`During King Author's time, one of the knights of the round table collected taxes.  His name was Sir Charge.`,
	`What did the fried rice say to the shrimp? Don't wak away from me!`,
	`Did you hear Steve Harvey and his wife got into a fight? It was a family fued`,
	`Did you hear about the superhero with a lisp that always worked out? He's thor`,
	`What kind of car does an egg drive? A Yolkswagen.`,
	`What do you call someone who gets mad when they don't have any bread?  Lack toast intolerant.`,
	`What do you call the syrup with the speech impediment? Mrs. Stuttersworth`,
	`What airlines did Jesus and Mary take? Virgin.`,
	`What's the most crunk place  to go to the bathroom? The Lil Jon`,
	`What was teh foot's favorite type of chips? Dori-toes`,
	`If Steven Seagal removed all animal products from his diet, what would we call him? Vegan Seagal`,
	`What did the plumber say to the singer? Nice pipes.`,
	`If spaghetti made an action movie, what would it be called? Mission: Impastable`,
	`What kind of shoes do gophers wear? Wood chucks.`,
	`What do you call a lazy doctor? Dr. Do Little`,
	`What did the pot eat on its birthday? Pancakes.`,
	`Where would you grow a chef? Bakersfield.`,
	`Why did the salad go to the studio?  To get some beets.`,
	`A CPU predicts you will walk into a bar, you do not. Your wallet has been stolen.`,
	`One windmill says to the other, "What kind of music do you like".  To which the other responds with, "I'm a big metal fan."`,
	`What's the difference between USA and USB? One connects to all of your devices and accesses the data, the other is a hardware standard.`,
	`Why couldn't 8 get back up?  When it fell, it was forever.`,
	`Why did the hipster drown? Went ice skating on the pond before it was cool and fell into the mainstream.`,
	`You got to hand it to short people.. Because they can't reach it on their own.`,
	`To the person who stole my copy of Microsoft Office, I will find you.  You have my word!`,
	`Did you hear about the man who got cooled to absolute zero?.. He's 0K now.`,
	`If you need to wait a long time, try eating a clock, it's very time consuming.`,
}
